/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasiPenjualan;

import java.awt.Image;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.ImageIcon;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.Date;



/**
 *
 * @author faish
 */
public class admin_tambahFilm extends javax.swing.JFrame {

    /**
     * Creates new form dashboard_admin
     */
    String s;
    public admin_tambahFilm() {
        initComponents();
        // Central
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x,y);
        
         //SCALING TO FIT
        ImageIcon bg = new ImageIcon("C:\\Users\\faish\\Documents\\NetBeansProjects\\tubesPBO\\src\\gambar\\bekgronz.jpg");
        Image img1 = bg.getImage();
        Image img2 = img1.getScaledInstance(labelBG.getWidth(),labelBG.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledImg = new ImageIcon(img2);
        labelBG.setIcon(scaledImg);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        tf_idFilm = new javax.swing.JTextField();
        tf_namaFilm = new javax.swing.JTextField();
        tf_kuotaFilm = new javax.swing.JTextField();
        addFilmBTN = new javax.swing.JButton();
        browseBTN = new javax.swing.JButton();
        previewPoster = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_sinopsis = new javax.swing.JTextArea();
        labelBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 90, 30));

        tf_idFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idFilmActionPerformed(evt);
            }
        });
        jPanel1.add(tf_idFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 340, -1));
        jPanel1.add(tf_namaFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 340, -1));
        jPanel1.add(tf_kuotaFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 340, -1));

        addFilmBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addFilmBTN.setText("TAMBAH");
        addFilmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFilmBTNActionPerformed(evt);
            }
        });
        jPanel1.add(addFilmBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 140, -1));

        browseBTN.setText("BROWSE");
        browseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBTNActionPerformed(evt);
            }
        });
        jPanel1.add(browseBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, -1, -1));

        previewPoster.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(previewPoster, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 140, 180));
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 180));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 28)); // NOI18N
        jLabel7.setText("POSTER");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 28)); // NOI18N
        jLabel8.setText("ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 28)); // NOI18N
        jLabel9.setText("NAMA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 28)); // NOI18N
        jLabel10.setText("TANGGAL");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 28)); // NOI18N
        jLabel11.setText("SINOPSIS");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rota", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("S I L A H K A N   T A M B A H   F I L M");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 700, 80));

        jLabel3.setBackground(new java.awt.Color(255, 102, 51));
        jLabel3.setFont(new java.awt.Font("Rota", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bekgronz.jpg"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 110));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 28)); // NOI18N
        jLabel12.setText("KUOTA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        tf_sinopsis.setColumns(20);
        tf_sinopsis.setLineWrap(true);
        tf_sinopsis.setRows(5);
        tf_sinopsis.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tf_sinopsis);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 340, 200));
        jPanel1.add(labelBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFilmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFilmBTNActionPerformed
        // TODO add your handling code here:
     
        String ID = tf_idFilm.getText();
        String NAMA = tf_namaFilm.getText();
        Date TANGGAL = tf_tanggalFilm.getDate();
        String KUOTA = tf_idFilm.getText();
        String SINOPSIS = tf_sinopsis.getText();

        
        if (ID.isEmpty() || NAMA.isEmpty() || TANGGAL == null || KUOTA.isEmpty() || SINOPSIS.isEmpty()){
            JOptionPane.showMessageDialog(this,"Tolong isi kembali", "ups Error",JOptionPane.ERROR_MESSAGE);
        }else{
            Connection dbconn = koneksi.connectDB();
        try{
            PreparedStatement st = dbconn.prepareStatement
                ("INSERT INTO films(`id_film`, `nama_film`, `tanggal_film`, `kuota_film`, `img`, `sinopsis`) values(?,?,?,?,?,?)");
            InputStream is = new FileInputStream(new File(s));
            st.setString(1, tf_idFilm.getText());
            st.setString(3, ((JTextField)tf_tanggalFilm.getDateEditor().getUiComponent()).getText());
            st.setString(2, tf_namaFilm.getText());
            st.setString(4, tf_kuotaFilm.getText());
            st.setBlob(5, is);
            st.setString(6, tf_sinopsis.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Film sudah masuk");
            dashboard_admin da = new dashboard_admin();
            da.setVisible(true);
            this.dispose();
        }catch(Exception ex){
            ex.printStackTrace();
        }
        }
        
//        
    }//GEN-LAST:event_addFilmBTNActionPerformed

    private void tf_idFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idFilmActionPerformed

    private void browseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBTNActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            previewPoster.setIcon(ResizeImage(path));
            s = path;
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("Tidak ada Data");
        }
    }//GEN-LAST:event_browseBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dashboard_admin da = new dashboard_admin();
        da.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_tambahFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_tambahFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_tambahFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_tambahFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_tambahFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFilmBTN;
    private javax.swing.JLabel admin;
    private javax.swing.JButton browseBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBG;
    private javax.swing.JLabel previewPoster;
    private javax.swing.JTextField tf_idFilm;
    private javax.swing.JTextField tf_kuotaFilm;
    private javax.swing.JTextField tf_namaFilm;
    private javax.swing.JTextArea tf_sinopsis;
    // End of variables declaration//GEN-END:variables

    private Icon ResizeImage(String path) {
        ImageIcon MyImage = new ImageIcon(path);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(previewPoster.getWidth(), previewPoster.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
}
    
