/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasiPenjualan;
 
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
//import aplikasiPenjualan.dashboard_users;




/**
 *
 * @author faish
 */
public class pilih_film extends javax.swing.JFrame {

    private Object ex;
    
    
    

    /**
     * Creates new form home_users
     */
    public pilih_film() {
        initComponents();
        
        // TRANSPARAN
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(null);
        
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        
        textArea.setBorder(null);
        textArea.setBackground(new Color(0,0,0,20));
        
        tfSinopsis.setBorder(null);
        tfSinopsis.setBackground(new Color(0,0,0,20));

        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        
        this.setLocation(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_jumlahTiket = new javax.swing.JTextField();
        tf_idTiket = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        kembali = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(posterFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 200, 320));

        tf_jumlahTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_jumlahTiketActionPerformed(evt);
            }
        });
        jPanel1.add(tf_jumlahTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 130, -1));

        tf_idTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idTiketActionPerformed(evt);
            }
        });
        jPanel1.add(tf_idTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 130, -1));

        idFilm.setFont(new java.awt.Font("Lucida Sans", 3, 18)); // NOI18N
        idFilm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idFilm.setToolTipText("");
        jPanel1.add(idFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 60));

        jLabel2.setText("JUMLAH TIKET");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, 20));

        jButton1.setText("BELI TIKET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, -1, -1));

        tfSinopsis.setColumns(20);
        tfSinopsis.setFont(new java.awt.Font("Rota", 0, 18)); // NOI18N
        tfSinopsis.setLineWrap(true);
        tfSinopsis.setRows(5);
        tfSinopsis.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tfSinopsis);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 460, 250));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 480, 590));

        judulFilm_pilih.setFont(new java.awt.Font("AR DESTINE", 0, 18)); // NOI18N
        judulFilm_pilih.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(judulFilm_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, 80));

        kembali.setBackground(new java.awt.Color(242, 242, 242));
        kembali.setFont(new java.awt.Font("Rota ExtBd", 0, 36)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/AVATAR.png"))); // NOI18N
        kembali.setText("KEMBALI");
        kembali.setAlignmentX(1.0F);
        kembali.setAlignmentY(0.0F);
        kembali.setAutoscrolls(true);
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kembali.setIconTextGap(1);
        kembali.setMargin(new java.awt.Insets(25, 14, 3, 14));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 210, 60));

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        welcomeName.setFont(new java.awt.Font("AR DESTINE", 0, 36)); // NOI18N
        jPanel1.add(welcomeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 270, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bekgron.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(null,"Apakah yakin Logout?",
                "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if (pilih == JOptionPane.OK_OPTION){            
            pilih_film du = new pilih_film();
            dispose();
            menu_utama mu = new menu_utama();
            mu.setVisible(true);
            
                                            
        } else {
            JOptionPane.getRootFrame();
            
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        new dashboard_users().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_kembaliActionPerformed

    private void tf_idTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idTiketActionPerformed

    private void tf_jumlahTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_jumlahTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_jumlahTiketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String id = tf_idTiket.getText();
        String jumlah = tf_jumlahTiket.getText();
        if(id.isEmpty() || jumlah.isEmpty()){
            JOptionPane.showMessageDialog(this,"Tolong isi kembali", "ups Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            int pilih = JOptionPane.showConfirmDialog(null,"Apakah yakin untuk beli film ini?",
                "KONFIRMASI", JOptionPane.OK_CANCEL_OPTION);
            if (pilih == JOptionPane.OK_OPTION){
                reduceQuota(id,jumlah);
            }else{
                JOptionPane.getRootFrame();
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilih_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilih_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilih_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilih_film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilih_film().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    public static final javax.swing.JLabel idFilm = new javax.swing.JLabel();
    private javax.swing.JButton jButton1;
    public static final transient javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static final transient javax.swing.JLabel judulFilm_pilih = new javax.swing.JLabel();
    private javax.swing.JButton kembali;
    public static final javax.swing.JLabel posterFilm = new javax.swing.JLabel();
    public static final javax.swing.JTextArea textArea = new javax.swing.JTextArea();
    public static final javax.swing.JTextArea tfSinopsis = new javax.swing.JTextArea();
    private javax.swing.JTextField tf_idTiket;
    private javax.swing.JTextField tf_jumlahTiket;
    public static final javax.swing.JLabel welcomeName = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    private void reduceQuota(String id, String jumlah) {
        Connection dbconn = koneksi.connectDB();
        if(dbconn != null){
            try{
                PreparedStatement st = (PreparedStatement)
                        dbconn.prepareStatement("INSERT INTO films_out (id_film, jumlah) VALUES(?,?)");
                
                st.setString(1, id);
                st.setString(2, jumlah);
                
                int res = st.executeUpdate();
                JOptionPane.showMessageDialog(this, "TIKET FILM BERHASIL DIBELI!","BERHASIL", 
                        JOptionPane.INFORMATION_MESSAGE);
            }catch(SQLException ex){
            }Logger.getLogger(menuUpdateFilm.class.getName()).log(Level.SEVERE,null,ex);
        }else{
                System.out.println("Database tidak tersedia");
                }
    }
    
}
